import './globals.css'
import { Poppins } from 'next/font/google'
import { Inter } from 'next/font/google'
import Navbar from './components/Header'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin']
})  


export const metadata = {
  title: 'Github Profile Viewer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar/>
        <main className='container'>{children}</main>
      </body>
    </html>
  )
}

